services:

  # mkdocs - documentation
  mkdocs:
    build: .
    ports:
      - 8024:8001 # port mapping for the mkdocs serve command
    command: mkdocs serve
    restart: always
    volumes:
      - .:/app/

