# Key metadata about the site
site_name: !ENV SITE_NAME
site_description: !ENV SITE_DESCRIPTION
site_author: !ENV SITE_AUTHOR
site_url: !ENV SITE_URL

# MkDocs processes files in this folder into a HTML site
docs_dir: clinical-safety-management-file

# Copyright information which is shown in the footer
copyright: !ENV COPYRIGHT_TEXT

# these lines configure the 'GitHub repo' widget on the top right
repo_url: !ENV REPOSITORY_URL
repo_name: !ENV REPOSITORY_NAME
edit_uri: blob/main/clinical-safety-management-file

# `mkdocs serve` serves the docs locally on this (arbitrarily chosen) port
dev_addr: "127.0.0.1:8002"

# Navigation structure
nav:
  - Home: "index.md"
  - "clinical-safety-management-system.md"
  - "clinical-safety-management-plan.md"
  - "clinical-safety-case-report.md"
  - "hazard-log.md"
  - "business-continuity.md"
  - "security.md"
  - "third-party-tools-safety-assmt.md"
  - "medical-device.md"
  - "download.md"
  - "contact.md"
  - "license.md"

# theme settings, fonts, colours
theme:
  name: material

  # replace these path or the contents of the files to change the logo and favicon
  logo: _assets/_images/logo.png
  favicon: _assets/_images/favicon.png

  features:
    - navigation.instant
    # uncomment the below two lines for Tabbed navigation (along the header bar)
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.expand
    # - toc.integrate

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    code: Roboto Mono

# mkdocs plugins
plugins:
  - git-committers:
      repository: !ENV REPOSITORY_URL
      branch: main
      enabled: !ENV [ENABLE_GIT_COMMITTERS, false] # makes Git Committers optional
  - git-revision-date-localized:
      enable_creation_date: true
  - macros
  - search
  - with-pdf:
      #cover: false
      #back_cover: true
      #cover_subtitle: SUBTITLE TEXT
      #custom_template_path: TEMPLATES PATH
      #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      output_path: !ENV PDF_OUTPUT_PATH
      enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true

# additional markdown features
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true

# set extra CSS file
extra_css:
  - _assets/_stylesheets/extra.css

# Placeholder variables for {{ macros }} are set here
extra:
  author_email: !ENV AUTHOR_EMAIL
  author_name: !ENV AUTHOR_NAME
  clinical_safety_management_file_license: !ENV CLINICAL_SAFETY_MANAGEMENT_FILE_LICENSE
  clinical_safety_management_file_version: !ENV CLINICAL_SAFETY_MANAGEMENT_FILE_VERSION
  clinical_safety_officer_contact: !ENV CLINICAL_SAFETY_OFFICER_CONTACT
  clinical_safety_officer_github_handle: !ENV CLINICAL_SAFETY_OFFICER_GITHUB_HANDLE
  clinical_safety_officer_name: !ENV CLINICAL_SAFETY_OFFICER_NAME
  clinical_safety_team_name: !ENV CLINICAL_SAFETY_TEAM_NAME
  copyright_text: !ENV COPYRIGHT_TEXT
  enable_git_committers: !ENV ENABLE_GIT_COMMITTERS
  enable_pdf_export: !ENV ENABLE_PDF_EXPORT
  hazard_log_url: !ENV HAZARD_LOG_URL
  organisation_name: !ENV ORGANISATION_NAME
  pdf_output_path: !ENV PDF_OUTPUT_PATH
  project_name: !ENV PROJECT_NAME
  project_short_description: !ENV PROJECT_SHORT_DESCRIPTION
  project_slug: !ENV PROJECT_SLUG
  project_slug: !ENV PROJECT_SLUG
  repository_url: !ENV REPOSITORY_URL
  security_responsible_disclosure_email: !ENV SECURITY_RESPONSIBLE_DISCLOSURE_EMAIL
  site_author: !ENV SITE_AUTHOR
  site_description: !ENV SITE_DESCRIPTION
  site_name: !ENV SITE_NAME
  site_url: !ENV SITE_URL
  # uncomment to add social icons
  # social:
  #   - icon: fontawesome/brands/twitter
  #     link: https://twitter.com/exampleorgstwitter
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/exampleorgsgithub
