# Key metadata about the site
site_name: "Digital Clinical Safety Alliance"
site_description: "A template for creating clinical safety management files"
site_author: "Digital Clinical Safety Alliance Team"
site_url: "https://www.digital-clinical-safety-alliance.org"

# MkDocs processes files in this folder into a HTML site
docs_dir: clinical-safety-management-file

# Copyright information which is shown in the footer
copyright: "Copyright &copy; 2025"

# these lines configure the 'GitHub repo' widget on the top right
repo_url: "https://github.com/clinicians-who-code/clinical-safety-hazard-documentation"
repo_name: "clinical-safety-hazard-documentation"
edit_uri: blob/main/clinical-safety-management-file

# `mkdocs serve` serves the docs locally on this (arbitrarily chosen) port
dev_addr: "0.0.0.0:8001"

# Navigation structure
nav:
  - Home: "index.md"
  - "clinical-safety-management-system.md"
  - "clinical-safety-management-plan.md"
  - "clinical-safety-case-report.md"
  - "hazard-log.md"
  - "business-continuity.md"
  - "security.md"
  - "third-party-tools-safety-assmt.md"
  - "medical-device.md"
  - "download.md"
  - "contact.md"
  - "license.md"

# theme settings, fonts, colours
theme:
  name: material

  # replace these path or the contents of the files to change the logo and favicon
  logo: _assets/_images/logo.png
  favicon: _assets/_images/favicon.png

  features:
    - navigation.instant
    # uncomment the below two lines for Tabbed navigation (along the header bar)
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.expand
    # - toc.integrate

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    code: Roboto Mono

# mkdocs plugins
plugins:
  - git-committers:
      repository: "**REPOSITORY_URL**"
      branch: main
      enabled:  false # makes Git Committers optional
  - git-revision-date-localized:
      enable_creation_date: true
  - macros
  - search
  - with-pdf:
      #cover: false
      #back_cover: true
      #cover_subtitle: SUBTITLE TEXT
      #custom_template_path: TEMPLATES PATH
      #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      # output_path: 
      # enabled_if_env: 
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true

# additional markdown features
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true

# set extra CSS file
extra_css:
  - _assets/_stylesheets/extra.css

# Placeholder variables for {{ macros }} are set here
extra:
  author_email: "author@example.com"
  author_name: "Example Author's Name"
  clinical_safety_management_file_license: "Creative Commons CC-BY-SA4.0"
  clinical_safety_management_file_version: "1.0.0"
  clinical_safety_officer_contact: "clinicalsafetyofficer@example.com"
  clinical_safety_officer_github_handle: "csogithubhandle"
  clinical_safety_officer_name: "Clinical Safety Officer Name"
  clinical_safety_team_name: "Clinical Safety Team Name"
  enable_git_committers: false
  enable_pdf_export: false
  hazard_log_url: "https://github.com/clinicians-who-code/clinical-safety-hazard-documentation/issues"
  organisation_name: "A Healthcare Technology Company"
  pdf_output_path: "pdf/clinical-safety-management-file.pdf"
  project_name: "Healthcare Technology Project Name"
  project_short_description: "A Template for a Clinical Safety Management File"
  project_slug: "https://github.com/clinicians-who-code/clinical-safety-hazard-documentation"
  repository_url: "https://github.com/clinicians-who-code/clinical-safety-hazard-documentation"
  security_responsible_disclosure_email: "securityresponsibledisclosure@example.com"
  site_author: "Digital Clinical Safety Alliance Team"
  site_description: "A template for creating clinical safety management files"
  site_name: "Digital Clinical Safety Alliance"
  site_url: "https://www.digital-clinical-safety-alliance.org"

